# Generated by Django 6.0.6 on 2026-07-13 10:52

import uuid

import django.db.models.deletion
from django.db import migrations, models

GATEWAY_METHODS = ['fonepay', 'esewa', 'khalti']


def backfill_legacy_intents(apps, schema_editor):
    """
    Digital payments taken before gateway verification existed have no proof behind
    them — a cashier chose 'eSewa' and typed a reference, and the system believed it.

    They cannot be verified retroactively: the gateway was never asked. Deleting them
    would destroy sales history, and inventing a 'verified' intent would launder them
    into looking checked. So each one gets an intent explicitly marked `legacy`, which
    is queryable — every unproven rupee ever taken can be listed with one filter.
    """
    Payment = apps.get_model('sales', 'Payment')
    PaymentIntent = apps.get_model('payments', 'PaymentIntent')

    legacy = Payment.objects.filter(method__in=GATEWAY_METHODS, intent__isnull=True).select_related('order')
    for payment in legacy.iterator():
        intent = PaymentIntent.objects.create(
            gateway='legacy',
            status='consumed',
            amount_paisa=payment.amount_paisa,
            prn=uuid.uuid4().hex,
            gateway_ref=(payment.ref or '')[:128] or None,
            location_id=payment.order.fulfilled_location_id,
            session_id=payment.order.session_id,
            created_by=None,
            failure_reason='Backfilled: taken before gateway verification existed; never confirmed with any gateway.',
        )
        payment.intent = intent
        payment.save(update_fields=['intent'])


def drop_legacy_intents(apps, schema_editor):
    Payment = apps.get_model('sales', 'Payment')
    PaymentIntent = apps.get_model('payments', 'PaymentIntent')
    Payment.objects.filter(intent__gateway='legacy').update(intent=None)
    PaymentIntent.objects.filter(gateway='legacy').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_allow_null_created_by'),
        ('sales', '0003_cashiersession_open_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='intent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='payments.paymentintent'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('fonepay', 'Fonepay QR'), ('esewa', 'eSewa'), ('khalti', 'Khalti')], max_length=20),
        ),
        # Label the unprovable history BEFORE the constraint goes on, or it rejects
        # the very rows it exists to flag.
        migrations.RunPython(backfill_legacy_intents, drop_legacy_intents),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('intent__isnull', False), ('method__in', ['khalti', 'fonepay', 'esewa'])), models.Q(('method__in', ['khalti', 'fonepay', 'esewa']), _negated=True), _connector='OR'), name='gateway_payment_requires_verified_intent'),
        ),
    ]
