# Generated by Django 6.0.6 on 2026-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_allow_null_created_by'),
        ('sales', '0004_payment_intent_alter_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='gateway_payment_requires_verified_intent',
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('intent__isnull', False), ('method__in', ['esewa', 'fonepay', 'khalti'])), models.Q(('method__in', ['esewa', 'fonepay', 'khalti']), _negated=True), _connector='OR'), name='gateway_payment_requires_verified_intent'),
        ),
    ]
