# Generated by Django 5.2.16 on 2026-07-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_payment_gateway_payment_requires_verified_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_txn_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
