# Generated by Django 6.0.6 on 2026-06-22 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='partners.customer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('warehouse', 'Warehouse Staff'), ('procurement', 'Procurement'), ('customer', 'Customer')], default='cashier', max_length=20),
        ),
    ]
