# Generated by Django 6.0.6 on 2026-06-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_customer_alter_user_role'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_locations',
            field=models.ManyToManyField(blank=True, related_name='outlet_managers', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('manager', 'Manager'), ('outlet_manager', 'Outlet Manager'), ('cashier', 'Cashier'), ('warehouse', 'Warehouse Staff'), ('procurement', 'Procurement'), ('customer', 'Customer')], default='cashier', max_length=20),
        ),
    ]
