# Generated by Django 6.0.6 on 2026-06-22 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('source_type', models.CharField(choices=[('own', 'Own'), ('external', 'External')], max_length=10)),
                ('live_weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bird_count', models.PositiveIntegerField()),
                ('accumulated_cost_paisa', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('arrival', 'Arrival'), ('grading', 'Grading'), ('storage', 'Storage'), ('slaughter', 'Slaughter'), ('packaging', 'Packaging'), ('sale', 'Sale'), ('settlement', 'Settlement')], default='arrival', max_length=20)),
                ('arrival_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrived_lots', to='locations.location')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='partners.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
