# Generated by Django 6.0.6 on 2026-07-13 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('sales', '0003_cashiersession_open_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(choices=[('fonepay', 'Fonepay QR'), ('mock', 'Mock (test/demo)')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Awaiting payment'), ('verified', 'Verified by gateway'), ('consumed', 'Attached to an order'), ('failed', 'Failed or rejected'), ('expired', 'Expired')], default='initiated', max_length=20)),
                ('amount_paisa', models.PositiveBigIntegerField()),
                ('prn', models.CharField(editable=False, max_length=64, unique=True)),
                ('gateway_ref', models.CharField(blank=True, max_length=128, null=True)),
                ('qr_payload', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='locations.location')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='sales.cashiersession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='pay_intent_status_idx')],
            },
        ),
    ]
