# Generated by Django 6.0.6 on 2026-07-13 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='gateway',
            field=models.CharField(choices=[('fonepay', 'Fonepay QR'), ('mock', 'Mock (test/demo)'), ('legacy', 'Legacy (unverified — pre-dates gateway checks)')], max_length=20),
        ),
    ]
