# Generated by Django 5.2.16 on 2026-07-29 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_price_active_unique'),
        ('inventory', '0001_initial'),
        ('locations', '0001_initial'),
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['type', 'ref_id'], name='inv_mov_type_ref_idx'),
        ),
    ]
