# Generated by Django 6.0.6 on 2026-06-22 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('uom', models.CharField(choices=[('kg', 'Kilogram'), ('piece', 'Piece')], max_length=10)),
                ('is_weighed', models.BooleanField(default=False)),
                ('tax_class', models.CharField(choices=[('exempt', 'Exempt'), ('taxable', 'Taxable (13% VAT)')], default='exempt', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('member', 'Member')], max_length=20)),
                ('price_paisa', models.PositiveIntegerField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.product')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
    ]
