# Generated by Django 6.0.6 on 2026-06-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('product', 'tier'), name='unique_active_price_per_product_tier'),
        ),
    ]
