# Generated by Django 6.0.6 on 2026-06-22 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_at', models.DateTimeField()),
                ('input_weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('output_weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_runs', to='lots.lot')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
